service: bunlar-backend

plugins:
  - serverless-offline
  - serverless-plugin-warmup
  - serverless-plugin-optimize

custom:
  warmup:

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-central-1
  timeout: 20
  memorySize: 128

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
