service: bunlar-backend

plugins:
  - serverless-offline
  - serverless-plugin-optimize
  - serverless-plugin-warmup
useDotenv: true
custom:
  serverless-offline:
    noPrependStageInUrl: true
  warmup:
    enabled: true
    concurrency: 2
    prewarm: true
    schedule: rate(5 minutes)
    source: { 'type': 'keepLambdaWarm' }
    sourceRaw: true
    timeout: 60

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs16.x
  region: eu-central-1
  timeout: 20
  memorySize: 256
  environment:
    SYSTEM_ID: jdoe

functions:
  main:
    warmup:
      enabled: true
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
